apiVersion: v1
kind: Service
metadata:
  name: oracle
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: oracle
  ports:
  - name: tns
    protocol: TCP
    port: 1521
    targetPort: 1521