{{- if .Values.oracle.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oracle-pvc
  namespace: {{ .Values.global.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.oracle.persistence.size }}
  storageClassName: {{ .Values.oracle.persistence.storageClass }}
{{- end}}