{{- if and .Values.oracle.env.ORACLE_PASSWORD .Values.backend.env.DB_USER .Values.backend.env.DB_PASS }}
apiVersion: v1
kind: Secret
metadata:
  name: oracle-secret
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  ORACLE_PASSWORD: {{ .Values.oracle.env.ORACLE_PASSWORD | b64enc }}
  DB_USER: {{ .Values.backend.env.DB_USER | b64enc }}
  DB_PASS: {{ .Values.backend.env.DB_PASS | b64enc }}
{{- end }}

