apiVersion: v1
kind: Secret
metadata:
  name: oracle-secret
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  ORACLE_PASSWORD: {{ required "Set --set oracle.env.ORACLE_PASSWORD=xxx" .Values.oracle.env.ORACLE_PASSWORD | b64enc }}
  DB_USER: {{ required "Set --set backend.env.DB_USER=xxx" .Values.backend.env.DB_USER | b64enc }}
  DB_PASS: {{ required "Set --set backend.env.DB_PASS=xxx" .Values.backend.env.DB_PASS | b64enc }}

